### ISSUE TITLE
There is sth that I think it is wrong in this code.

### ISSUE THREAD

**Issue by hezw2016** [tegg89/SRCNN-Tensorflow#4]
'''
input_ = scipy.ndimage.interpolation.zoom(label_, .5, prefilter=False)    
input_ = scipy.ndimage.interpolation.zoom(input_, 2, prefilter=False)  
'''

.5 and 2???? I think they should be 1/3. and 3. Because the scale is 3.

By the way, this code helps me a lot.

**Comment by hezw2016** [comment]
I have also got this problem：
hezewei@ubuntu:~/SRCNN-Tensorflow$ python main.py --is_train False --stride 21
{'batch_size': 128,
 'c_dim': 1,
 'checkpoint_dir': 'checkpoint',
 'epoch': 10,
 'image_size': 33,
 'is_train': False,
 'label_size': 21,
 'learning_rate': 0.0001,
 'sample_dir': 'sample',
 'scale': 3,
 'stride': 21}
 [*] Reading checkpoints...
 [*] Load SUCCESS
Testing...
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 43, in main
    srcnn.train(FLAGS)
  File "/home/hezewei/SRCNN-Tensorflow/model.py", line 112, in train
    imsave(merge, os.path.join(os.getcwd(), config.sample_dir))
  File "/home/hezewei/SRCNN-Tensorflow/utils.py", line 191, in imsave
    return scipy.misc.imsave(path, image)
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 195, in imsave
    im = toimage(arr, channel_axis=2)
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 287, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.

how to solve this?

**Comment by tegg89** [comment]
@hezw2016 Thanks a lot for your comments! I am just a student learning deep learning by myself. Your advice helps me understand python library better :)
(I will change scale thing and squeeze one later!)
